export '../../widgets/newButton.dart';
export '../../widgets/newContainer.dart';
export '../../widgets/seleccionOpcion.dart';
export '../../widgets/subTitulo.dart';
export 'asignarFechaProyecto.dart';
export 'proyect.dart';
export 'widgets/agregarProyecto.dart';
export 'widgets/buscarCurso.dart';
export 'widgets/cuadroTabla.dart';
